
@baseUrl = http://localhost:3333

GET {{baseUrl}}/repositories HTTP/1.1
Content-Type: application/json
Accept: application/json

###

POST {{baseUrl}}/repositories HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title" : "My Repository",
  "url" : "http://localhost:3333/my-repository",
  "techs" : ["nodejs", "javascript"]
}

###

POST  {{baseUrl}}/repositories/387012a0-af07-4ea2-b2ff-3192480b0cff/like HTTP/1.1
Content-Type: application/json
Accept: application/json

###

PUT {{baseUrl}}/repositories/387012a0-af07-4ea2-b2ff-3192480b0cff HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title" : "My Repository",
  "url" : "http://localhost:3333/my-repository",
  "techs" : ["nodejs", "javascript", "Rest"],
  "likes" : 15
}

####

DELETE {{baseUrl}}/repositories/1c869a9f-7ae2-4104-969d-60d85b02d92c HTTP/1.1
Content-Type: application/json
Accept: application/json